spring:
  application:
    name: task-ui
  thymeleaf:
    cache: false

server:
  port: 8081
  servlet:
    session:
      timeout: 15m   # session timeout

backend:
  base-url: http://localhost:8080

logging:
  file:
      name: ./logs/task-ui.log
  level:
    org.springframework.security: TRACE

